# Generated by Django 6.0.7 on 2026-07-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clinical_data', models.JSONField(help_text='Raw clinical input: AGE, SEX, BMI, HbA1c, etc.')),
                ('risk_score', models.FloatField(help_text='ML-predicted risk score (0-100).')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], max_length=20)),
                ('prediction_confidence', models.FloatField(help_text='Model prediction confidence/probability (0-1).')),
                ('ai_treatment_suggestion', models.TextField(blank=True, help_text='LLM-generated treatment recommendation (populated async).', null=True)),
                ('confirmed_outcome', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED_YES', 'Confirmed Yes'), ('CONFIRMED_NO', 'Confirmed No')], default='PENDING', help_text='Clinician-confirmed outcome for model retraining.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
