# Generated by Django 6.0.7 on 2026-07-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='gnb_score',
            field=models.FloatField(blank=True, help_text='Gaussian Naive Bayes model risk score (0-100).', null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='knn_score',
            field=models.FloatField(blank=True, help_text='KNN model risk score (0-100).', null=True),
        ),
    ]
